
DROP TABLE SECURITY_ROLE CASCADE;
DROP TABLE ADMINISTRATOR_ACCOUNT CASCADE;
DROP TABLE SITE CASCADE;
DROP TABLE QUESTION_FORMAT CASCADE;
DROP TABLE MEAL CASCADE;
DROP TABLE AGE_RANGE CASCADE;
DROP TABLE GENDER CASCADE;
DROP TABLE QUESTION_TOPIC CASCADE;
DROP TABLE PARTICIPANT_TYPE CASCADE;
DROP TABLE POTENTIAL_SURVEY_WORD CASCADE;
DROP TABLE UNIT CASCADE;
DROP TABLE ADMINISTRATOR_ROLE CASCADE;
DROP TABLE SURVEY_VERSION CASCADE;
DROP TABLE QUESTION CASCADE;
DROP TABLE SURVEY_WORD CASCADE;
DROP TABLE SUBMITTED_SURVEY CASCADE;
DROP TABLE QUESTION_SELECTION CASCADE;
DROP TABLE PARTICIPANT_RESPONSE CASCADE;
DROP TABLE SURVEY_QUESTION CASCADE;
DROP EXTENSION pgcrypto;


CREATE EXTENSION pgcrypto;


-- create table for Security ROLE
CREATE TABLE SECURITY_ROLE
(
	SECURITY_ROLE_ID SERIAL PRIMARY KEY NOT NULL,
	SECURITY_DESCRIPTION VARCHAR(100) NOT NULL
);


-- create table Administrator Account
CREATE TABLE ADMINISTRATOR_ACCOUNT
(
	ADMINISTRATOR_ACCOUNT_ID SERIAL PRIMARY KEY NOT NULL,
	USERNAME VARCHAR(50) UNIQUE NOT NULL,
	ADMIN_PASSWORD VARCHAR(60) NOT NULL, -- Changed to VARCHAR(50) for hashing
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	ARCHIVE_YN BOOLEAN DEFAULT TRUE NOT NULL,
	DATE_CREATED TIMESTAMP DEFAULT NOW() NOT NULL,
	DATE_MODIFIED TIMESTAMP NULL
);
-- create table for Site
CREATE TABLE SITE
(
	SITE_ID SERIAL PRIMARY KEY NOT NULL,
	SITE_NAME VARCHAR(100) NOT NULL,
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	ARCHIVED_YN BOOL DEFAULT FALSE NOT NULL,
	
	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Question Format
CREATE TABLE QUESTION_FORMAT
(
	QUESTION_FORMAT_ID SERIAL PRIMARY KEY NOT NULL,
	QUESTION_FORMAT_NAME VARCHAR(100) NOT NULL
);

-- create table Meal
CREATE TABLE MEAL
(
	MEAL_ID SERIAL PRIMARY KEY NOT NULL,
	MEAL_NAME VARCHAR(100) NOT NULL,
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	ARCHIVED_YN BOOL DEFAULT FALSE NOT NULL,

	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Age
CREATE TABLE AGE_RANGE
(
	AGE_RANGE_ID SERIAL PRIMARY KEY NOT NULL,
	AGE_RANGE_DESCRIPTION VARCHAR(100) NOT NULL,
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	ARCHIVED_YN BOOL DEFAULT FALSE NOT NULL,

	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Gender
CREATE TABLE GENDER
(
	GENDER_ID SERIAL PRIMARY KEY NOT NULL,
	GENDER_DESCRIPTION VARCHAR(100) NOT NULL,
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	ARCHIVED_YN BOOL DEFAULT FALSE NOT NULL,

	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Question Topic
CREATE TABLE QUESTION_TOPIC
(
	QUESTION_TOPIC_ID SERIAL PRIMARY KEY NOT NULL,
	QUESTION_TOPIC_DESCRIPTION VARCHAR(100) NOT NULL
);

-- create table Participant
CREATE TABLE PARTICIPANT_TYPE
(
	PARTICIPANT_TYPE_ID SERIAL PRIMARY KEY NOT NULL,
	PARTICIPANT_DESCRIPTION VARCHAR(100) NOT NULL,
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	ARCHIVED_YN BOOL DEFAULT FALSE NOT NULL,

	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table for Potential Survey Word
CREATE TABLE POTENTIAL_SURVEY_WORD
(
	SURVEY_WORD_ID SERIAL PRIMARY KEY NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	SURVEY_ACCESS_WORD VARCHAR(8) NOT NULL,
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	ARCHIVE_YN BOOLEAN DEFAULT FALSE NOT NULL,
	
	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Unit
CREATE TABLE UNIT
(
	UNIT_ID SERIAL PRIMARY KEY NOT NULL,
	UNIT_NUMBER VARCHAR(100) NOT NULL,
	SITE_ID INT NOT NULL,
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	ARCHIVED_YN BOOL DEFAULT FALSE NOT NULL,	

	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID),
	FOREIGN KEY (SITE_ID) REFERENCES SITE (SITE_ID)
);

-- create table Administrator Role
CREATE TABLE ADMINISTRATOR_ROLE
(
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID),
	SECURITY_ROLE_ID INT NOT NULL REFERENCES SECURITY_ROLE (SECURITY_ROLE_ID),
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	
	PRIMARY KEY (ADMINISTRATOR_ACCOUNT_ID, SECURITY_ROLE_ID)
);

-- create table Survey Version
CREATE TABLE SURVEY_VERSION
(
	SURVEY_VERSION_ID SERIAL PRIMARY KEY NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	START_DATE TIMESTAMP DEFAULT NOW() NOT NULL, 
	END_DATE TIMESTAMP NULL,
	
	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Question
CREATE TABLE QUESTION
(
	QUESTION_ID SERIAL PRIMARY KEY NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	QUESTION_FORMAT_ID INT NOT NULL, 
	QUESTION_TOPIC_ID INT NOT NULL,
	QUESTION_TEXT VARCHAR(250) NOT NULL,
	DATE_CREATED TIMESTAMP DEFAULT NOW() NOT NULL,
	IS_EXTRA BOOLEAN DEFAULT FALSE NOT NULL,
	
	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID),
	FOREIGN KEY (QUESTION_FORMAT_ID) REFERENCES QUESTION_FORMAT (QUESTION_FORMAT_ID),
	FOREIGN KEY (QUESTION_TOPIC_ID) REFERENCES QUESTION_TOPIC (QUESTION_TOPIC_ID)
);

--create Table Survey Word
CREATE TABLE SURVEY_WORD
(
	SURVEY_WORD_ID INT REFERENCES POTENTIAL_SURVEY_WORD (SURVEY_WORD_ID) NOT NULL, 
	SITE_ID INT REFERENCES SITE (SITE_ID) NOT NULL,
	DATE_USED TIMESTAMP DEFAULT NOW() NOT NULL,
	
	PRIMARY KEY (SURVEY_WORD_ID, SITE_ID)
);

-- create table Submitted Survey
CREATE TABLE SUBMITTED_SURVEY
(
	SUBMITTED_SURVEY_ID SERIAL PRIMARY KEY NOT NULL,
	SURVEY_VERSION_ID INT NOT NULL,
	UNIT_ID INT NOT NULL,
	MEAL_ID INT NOT NULL,
	PARTICIPANT_TYPE_ID INT NOT NULL,
	AGE_RANGE_ID INT NOT NULL,
	GENDER_ID INT NOT NULL,
	DATE_ENTERED TIMESTAMP DEFAULT NOW() NOT NULL, 
	CONTACT_REQUEST BOOL NOT NULL DEFAULT FALSE,
	CONTACTED BOOL NOT NULL DEFAULT FALSE,
	CONTACT_ROOM_NUMBER VARCHAR(50) NULL,
	CONTACT_PHONE_NUMBER VARCHAR(20) NULL,
	
	FOREIGN KEY (SURVEY_VERSION_ID) REFERENCES SURVEY_VERSION (SURVEY_VERSION_ID),
	FOREIGN KEY (AGE_RANGE_ID) REFERENCES AGE_RANGE (AGE_RANGE_ID),
	FOREIGN KEY (UNIT_ID) REFERENCES UNIT (UNIT_ID),
	FOREIGN KEY (MEAL_ID) REFERENCES MEAL (MEAL_ID),
	FOREIGN KEY (PARTICIPANT_TYPE_ID) REFERENCES PARTICIPANT_TYPE (PARTICIPANT_TYPE_ID),
	FOREIGN KEY (GENDER_ID) REFERENCES GENDER (GENDER_ID)
);

-- create table Question Selection
CREATE TABLE QUESTION_SELECTION
(
	QUESTION_SELECTION_ID SERIAL PRIMARY KEY NOT NULL,
	QUESTION_ID INT NOT NULL,
	QUESTION_SELECTION_TEXT VARCHAR(100) NOT NULL,
	QUESTION_SELECTION_VALUE VARCHAR(100) NOT NULL,
	
	FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (QUESTION_ID)
);

-- create table Survey Question
CREATE TABLE PARTICIPANT_RESPONSE
(
	SUBMITTED_SURVEY_ID INT NOT NULL REFERENCES SUBMITTED_SURVEY (SUBMITTED_SURVEY_ID),
	QUESTION_ID INT NOT NULL REFERENCES QUESTION (QUESTION_ID),
	PARTICIPANT_ANSWER TEXT NULL,
	
	PRIMARY KEY (SUBMITTED_SURVEY_ID, QUESTION_ID)
);

-- create table Survey Question
CREATE TABLE SURVEY_QUESTION
(
	SURVEY_VERSION_ID INT NOT NULL REFERENCES SURVEY_VERSION (SURVEY_VERSION_ID),
	QUESTION_ID INT NOT NULL REFERENCES QUESTION (QUESTION_ID),
	
	PRIMARY KEY (SURVEY_VERSION_ID, QUESTION_ID)
);

-- Create password_is_valid function
CREATE OR REPLACE FUNCTION password_is_valid (
	username_param VARCHAR(50), 
	password_param VARCHAR(60))
RETURNS BOOLEAN AS $$
	DECLARE isValid BOOLEAN;
BEGIN
	IF username_param = '' OR username_param IS NULL OR password_param = '' OR password_param IS NULL THEN
		isValid = FALSE;
	ELSE	
		SELECT INTO isValid
		(admin_password = crypt(password_param, admin_password))
		FROM administrator_account
		WHERE username = username_param;
	END IF;
	RETURN isValid;
END; $$
LANGUAGE PLPGSQL;

-- Create add_user function
CREATE OR REPLACE FUNCTION add_user (
	username_param VARCHAR(50), 
	password_param VARCHAR(60),
	firstname_param VARCHAR(50),
	lastname_param VARCHAR(50),
	securityid_param INTEGER)
RETURNS VARCHAR(50) AS $$
DECLARE
	userID INTEGER;
	createdUsername VARCHAR(50);
BEGIN
	INSERT INTO administrator_account (username, admin_password, first_name, last_name, date_created)
	VALUES (username_param, crypt(password_param,gen_salt('bf')), firstname_param, lastname_param, NOW());
	
	SELECT administrator_account_id INTO userID
	FROM administrator_account
	WHERE username = username_param;
	
	INSERT INTO administrator_role (administrator_account_id, security_role_id, date_modified)
	VALUES (userID, securityid_param, NOW());
	
	SELECT username INTO createdUsername
	FROM administrator_account
	WHERE administrator_account_id = userID;
	
	RETURN createdUsername;
END; $$
LANGUAGE PLPGSQL;

-- Create Webmaster
INSERT INTO ADMINISTRATOR_ACCOUNT (USERNAME, ADMIN_PASSWORD, FIRST_NAME, LAST_NAME, DATE_CREATED, DATE_MODIFIED)
VALUES ('webmaster', crypt('password', gen_salt('bf')), 'Web', 'Master', Now(), NOW());
INSERT INTO ADMINISTRATOR_ACCOUNT (USERNAME, ADMIN_PASSWORD, FIRST_NAME, LAST_NAME, DATE_CREATED, DATE_MODIFIED)
VALUES ('ggerry', crypt('SecretPassword123', gen_salt('bf')), 'Garry', 'Gerry', Now(), NOW());


--Insert security roles
INSERT INTO security_role (security_description)
VALUES ('Standard Administrator');
INSERT INTO security_role (security_description)
VALUES ('Master Administrator');


--assign webmaster to Master ADministrator role
INSERT INTO ADMINISTRATOR_ROLE (ADMINISTRATOR_ACCOUNT_ID, SECURITY_ROLE_ID, DATE_MODIFIED)
VALUES (1, 2, NOW());
INSERT INTO ADMINISTRATOR_ROLE (ADMINISTRATOR_ACCOUNT_ID, SECURITY_ROLE_ID, DATE_MODIFIED)
VALUES (2,1,NOW());

--create misericordia's site
INSERT INTO SITE (SITE_NAME, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Misericordia Hospital', Now(), 1);

--creates Misericordia's units
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('8E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('7E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('5W', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('7W', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('6E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('6W', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('5E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('3E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('3N', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('ED', 1, Now(), 1);
--for those without a unit (nonpatients)
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Not Applicable', 1, Now(), 1);

--create potential survey words
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'sunshine', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'flower', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'supper', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'sleepy', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'hungry', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'happy', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'orange', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'friend', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'spring', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'circle', Now());

--create question formats
INSERT INTO QUESTION_FORMAT(QUESTION_FORMAT_NAME)
VALUES ('choice');
INSERT INTO QUESTION_FORMAT(QUESTION_FORMAT_NAME)
VALUES ('text');
--questions whose answers are also stored directly on the submitted_survey
--technically still a "choice" format 
INSERT INTO QUESTION_FORMAT(QUESTION_FORMAT_NAME)
VALUES ('demo');
--not really a question. 
INSERT INTO QUESTION_FORMAT(QUESTION_FORMAT_NAME)
VALUES ('header');
--not really a question; exits header format
INSERT INTO QUESTION_FORMAT(QUESTION_FORMAT_NAME)
VALUES ('exitheader');


--create question topics
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Variety');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Taste');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Temperature');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Appearance');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Staff Helpfulness');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Portion Size');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Diet Requirements');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Overall Experience');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Comment');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('None');
--
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Age Range');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Gender');

--create questions
--first the original questions
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 4, 10, 'During this hospital stay, how would you describe the following features of your meals?', Now(), false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 1, 1, 'The variety of food in your daily meals',Now(), false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 1, 2, 'The taste and flavour of your meals', Now(),false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 1, 3, 'The temperature of your hot food', Now(),false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 1, 4, 'The overall appearance of your meal', Now(),false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 1, 5, 'The helpfulness of the staff who deliver your meals',Now(), false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 5, 10, '',Now(), false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 1, 6, 'How satisfied are you with the portion sizes of your meals?',Now(), false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 1, 7, 'Do your meals take into account your specific diet requirements?',Now(), false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 1, 8, 'Overall, how would you rate your meal experience?', Now(),false);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 2, 9, 'Is there anything else you would like to share about your meal experience?',Now(), false);

--demographic questions -- UPDATE-March 15, demographic questions no longer needed, will be hardcoded
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 3, 12, 'Gender:',Now(), true);
INSERT INTO QUESTION(ADMINISTRATOR_ACCOUNT_ID, QUESTION_FORMAT_ID, QUESTION_TOPIC_ID, QUESTION_TEXT, DATE_CREATED, IS_EXTRA)
VALUES (1, 3, 11, 'Age Range:',Now(), true);

--create question selections
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (2, 'Very Good','Very Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (2, 'Good','Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (2, 'Fair','Fair');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (2, 'Poor','Poor');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (2, 'Don''t Know/No Opinion','Don''t Know/No Opinion');

INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (3, 'Very Good','Very Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (3, 'Good','Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (3, 'Fair','Fair');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (3, 'Poor','Poor');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (3, 'Don''t Know/No Opinion','Don''t Know/No Opinion');

INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (4, 'Very Good','Very Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (4, 'Good','Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (4, 'Fair','Fair');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (4, 'Poor','Poor');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (4, 'Don''t Know/No Opinion','Don''t Know/No Opinion');

INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (5, 'Very Good','Very Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (5, 'Good','Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (5, 'Fair','Fair');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (5, 'Poor','Poor');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (5, 'Don''t Know/No Opinion','Don''t Know/No Opinion');

INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (6, 'Very Good','Very Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (6, 'Good','Good');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (6, 'Fair','Fair');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (6, 'Poor','Poor');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (6, 'Don''t Know/No Opinion','Don''t Know/No Opinion');

INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (8, 'Portion sizes are too small','Portion sizes are too small');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (8, 'Portion sizes are just right','Portion sizes are just right');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (8, 'Portion sizes are too large','Portion sizes are too large');

INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (9, 'Always','Always');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (9, 'Usually','Usually');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (9, 'Occasionally','Occasionally');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (9, 'Never','Never');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (9, 'I do not have any specific dietary requirements','I do not have any specific dietary requirements');


--UPDATE march 15, removed 6th choice (terrible) to match other questions
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (10, 'Very Good','5');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (10, 'Good','4');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (10, 'Fair','3');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (10, 'Poor','2');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (10, 'Very Poor','1');

--
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (12, 'Male','1');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (12, 'Female','2');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (12, 'Other','3');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (12, 'Prefer not to answer','4');

INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (13, 'Under 18 years','1');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (13, '18 to 34 years','2');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (13, '35 to 54 years','3');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (13, '55 to 74 years','4');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (13, 'Over 75 years','5');
INSERT INTO QUESTION_SELECTION(QUESTION_ID, QUESTION_SELECTION_TEXT, QUESTION_SELECTION_VALUE)
VALUES (13, 'Prefer not to answer','6');


--create the empty survey version
INSERT INTO SURVEY_VERSION(ADMINISTRATOR_ACCOUNT_ID, START_DATE)
VALUES (1, Now());

--create survey questions (associate the questions with the survey version)
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,1);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,2);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,3);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,4);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,5);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,6);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,7);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,8);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,9);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,10);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,11);

INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,12);
INSERT INTO SURVEY_QUESTION(SURVEY_VERSION_ID, QUESTION_ID)
VALUES (1,13);

--create meals
INSERT INTO MEAL(MEAL_NAME, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Breakfast', Now(), 1);
INSERT INTO MEAL(MEAL_NAME, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Lunch', Now(), 1);
INSERT INTO MEAL(MEAL_NAME, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Supper', Now(), 1);
INSERT INTO MEAL(MEAL_NAME, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Tea/Snack', Now(), 1);
--value for no selection (?)
INSERT INTO MEAL(MEAL_NAME, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Unspecified', Now(), 1);

--create participant types
INSERT INTO PARTICIPANT_TYPE(PARTICIPANT_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES('Patient', Now(), 1);
INSERT INTO PARTICIPANT_TYPE(PARTICIPANT_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES('Non-Patient', Now(),1);

--create age-ranges
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Under 18 years', Now(), 1);
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('18 to 34 years', Now(), 1);
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('35 to 54 years', Now(), 1);
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('55 to 74 years', Now(), 1);
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Over 75 years', NOw(), 1);
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Prefer not to Answer', Now(), 1);

--create genders
INSERT INTO GENDER(GENDER_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Male', Now(), 1);
INSERT INTO GENDER(GENDER_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Female', Now(), 1);
INSERT INTO GENDER(GENDER_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Other', Now(), 1);
INSERT INTO GENDER(GENDER_DESCRIPTION, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Prefer not to Answer', Now(), 1);



----------------------------------------------------
--create dummy submitted surveys
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 1, 1, 1, 3,3,Now(), true, false, '101', '7805551234');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 2, 3, 1, 1,1,Now(), true, false, '222', '8883333');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 3, 3, 2, 4,2,Now(), false, false, '', '');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 4, 2, 1, 2,4,Now(), true, false, '333', '1110000');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 5, 4, 1, 5,2,Now(), true, false, '000', '4444444');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 6, 2, 2, 2,2,Now(), true, false, '2', '2222222');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 7, 3, 1, 3,3,Now(), true, false, '3', '3333333');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 8, 5, 2, 4,4,Now(), false, false, '', '');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 9, 1, 2, 1,4,Now(), false, false, '', '');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_REQUEST, CONTACTED, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 10, 2, 1, 1,1,Now(), false ,false, '111', '1111111');


--create dummy participant responses

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,2,'Very Good');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,3,'Very Good');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,4,'Very Good');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,5,'Poor');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,6,'Very Poor');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,8,'Too Small');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,9,'Never');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,10,'5');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,11,'The meal was great and everything tasted excellent. Loved the coffee.');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (1,12,'3');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (1,13,'3');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,2,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,3,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,4,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,5,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,6,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,8,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,9,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,10,'3');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (2,11,'Wooohoo');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (2,12,'1');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (2,13,'1');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,2,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,3,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,4,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,5,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,6,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,8,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,9,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,10,'3');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (3,11,'');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (3,12,'2');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (3,13,'4');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,2,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,3,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,4,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,5,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,6,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,8,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,9,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,10,'3');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (4,11,'');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (4,12,'4');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (4,13,'2');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,2,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,3,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,4,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,5,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,6,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,8,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,9,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,10,'3');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (5,11,'');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (5,12,'2');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (5,13,'5');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,2,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,3,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,4,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,5,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,6,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,8,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,9,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,10,'3');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (6,11,'i am bored');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (6,12,'2');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (6,13,'2');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,2,'Fair');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,3,'Fair');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,4,'Fair');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,5,'Fair');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,6,'Fair');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,8,'Just Right');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,9,'Usually');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,10,'4');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (7,11,'have you heard of salt?');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (7,12,'3');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (7,13,'3');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,2,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,3,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,4,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,5,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,6,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,8,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,9,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,10,'3');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (8,11,'d');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (8,12,'4');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (8,13,'4');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,2,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,3,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,4,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,5,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,6,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,8,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,9,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,10,'3');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (9,11,'I visited Misericordia Community Hospital the day Edmonton made headlines for being colder than both the North and the South Pole.

The temperature was a mind and body-numbing 37 C with the wind chill and yet Misericordia was doing a booming business. 

Maybe these people, having been cooped up with relatives too long during the holidays, needed a change of scenery.

Maybe they could not stomach the thought of one more turkey-based meal. Or, maybe, being winter-hardy Edmontonians, they just figured there was no better time to venture out for some crispy eel and a pint of Innis & Gunn. 

Whatever the reason, the cozy hospital located at 16940 87 Ave NW had a lovely, lively, post-Christmas vibe.');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (9,12,'4');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (9,13,'1');

INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,2,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,3,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,4,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,5,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,6,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,8,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,9,'');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,10,'3');
INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
VALUES (10,11,'Wooohoo');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (10,12,'1');
--INSERT INTO PARTICIPANT_RESPONSE(SUBMITTED_SURVEY_ID,QUESTION_ID,PARTICIPANT_ANSWER)
--VALUES (10,13,'1');
