
DROP TABLE SECURITY_ROLE CASCADE;
DROP TABLE ADMINISTRATOR_ACCOUNT CASCADE;
DROP TABLE SITE CASCADE;
DROP TABLE QUESTION_FORMAT CASCADE;
DROP TABLE MEAL CASCADE;
DROP TABLE AGE_RANGE CASCADE;
DROP TABLE GENDER CASCADE;
DROP TABLE QUESTION_TOPIC CASCADE;
DROP TABLE PARTICIPANT_TYPE CASCADE;
DROP TABLE POTENTIAL_SURVEY_WORD CASCADE;
DROP TABLE UNIT CASCADE;
DROP TABLE ADMINISTRATOR_ROLE CASCADE;
DROP TABLE SURVEY_VERSION CASCADE;
DROP TABLE QUESTION CASCADE;
DROP TABLE SURVEY_WORD CASCADE;
DROP TABLE SUBMITTED_SURVEY CASCADE;
DROP TABLE QUESTION_SELECTION CASCADE;
DROP TABLE PARTICIPANT_RESPONSE CASCADE;
DROP TABLE SURVEY_QUESTION CASCADE;
DROP EXTENSION pgcrypto;


CREATE EXTENSION pgcrypto;


-- create table for Security ROLE
CREATE TABLE SECURITY_ROLE
(
	SECURITY_ROLE_ID SERIAL PRIMARY KEY NOT NULL,
	SECURITY_DESCRIPTION VARCHAR(100) NOT NULL
);


-- create table Administrator Account
CREATE TABLE ADMINISTRATOR_ACCOUNT
(
	ADMINISTRATOR_ACCOUNT_ID SERIAL PRIMARY KEY NOT NULL,
	USERNAME VARCHAR(50) UNIQUE NOT NULL,
	ADMIN_PASSWORD VARCHAR(60) NOT NULL, -- Changed to VARCHAR(50) for hashing
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	ACTIVE_YN BOOLEAN DEFAULT TRUE NOT NULL,
	DATE_CREATED TIMESTAMP DEFAULT NOW() NOT NULL,
	DATE_MODIFIED TIMESTAMP NULL
);
-- create table for Site
CREATE TABLE SITE
(
	SITE_ID SERIAL PRIMARY KEY NOT NULL,
	SITE_NAME VARCHAR(100) NOT NULL,
	DATE_MODIFIED TIMESTAMP NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	IS_CLOSED_YN BOOL DEFAULT FALSE NOT NULL,
	
	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Question Format
CREATE TABLE QUESTION_FORMAT
(
	QUESTION_FORMAT_ID SERIAL PRIMARY KEY NOT NULL,
	QUESTION_FORMAT_NAME VARCHAR(100) NOT NULL
);

-- create table Meal
CREATE TABLE MEAL
(
	MEAL_ID SERIAL PRIMARY KEY NOT NULL,
	MEAL_NAME VARCHAR(100) NOT NULL
);

-- create table Age
CREATE TABLE AGE_RANGE
(
	AGE_RANGE_ID SERIAL PRIMARY KEY NOT NULL,
	AGE_RANGE_DESCRIPTION VARCHAR(100) NOT NULL
);

-- create table Gender
CREATE TABLE GENDER
(
	GENDER_ID SERIAL PRIMARY KEY NOT NULL,
	GENDER_DESCRIPTION VARCHAR(100) NOT NULL
);

-- create table Question Topic
CREATE TABLE QUESTION_TOPIC
(
	QUESTION_TOPIC_ID SERIAL PRIMARY KEY NOT NULL,
	QUESTION_TOPIC_DESCRIPTION VARCHAR(100) NOT NULL
);

-- create table Participant
CREATE TABLE PARTICIPANT_TYPE
(
	PARTICIPANT_TYPE_ID SERIAL PRIMARY KEY NOT NULL,
	PARTICIPANT_DESCRIPTION VARCHAR(100) NOT NULL
);

-- create table for Potential Survey Word
CREATE TABLE POTENTIAL_SURVEY_WORD
(
	SURVEY_WORD_ID SERIAL PRIMARY KEY NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	SURVEY_ACCESS_WORD VARCHAR(8) NOT NULL,
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	ARCHIVE_YN BOOLEAN DEFAULT FALSE NOT NULL,
	
	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Unit
CREATE TABLE UNIT
(
	UNIT_ID SERIAL PRIMARY KEY NOT NULL,
	UNIT_NUMBER VARCHAR(100) NOT NULL,
	SITE_ID INT NOT NULL,
	DATE_MODIFIED TIMESTAMP NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	IS_CLOSED_YN BOOL DEFAULT FALSE NOT NULL,	

	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID),
	FOREIGN KEY (SITE_ID) REFERENCES SITE (SITE_ID)
);

-- create table Administrator Role
CREATE TABLE ADMINISTRATOR_ROLE
(
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID),
	SECURITY_ROLE_ID INT NOT NULL REFERENCES SECURITY_ROLE (SECURITY_ROLE_ID),
	DATE_MODIFIED TIMESTAMP DEFAULT NOW() NOT NULL,
	
	PRIMARY KEY (ADMINISTRATOR_ACCOUNT_ID, SECURITY_ROLE_ID)
);

-- create table Survey Version
CREATE TABLE SURVEY_VERSION
(
	SURVEY_VERSION_ID SERIAL PRIMARY KEY NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	START_DATE TIMESTAMP DEFAULT NOW() NOT NULL, 
	END_DATE TIMESTAMP NULL,
	
	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID)
);

-- create table Question
CREATE TABLE QUESTION
(
	QUESTION_ID SERIAL PRIMARY KEY NOT NULL,
	ADMINISTRATOR_ACCOUNT_ID INT NOT NULL,
	QUESTION_FORMAT_ID INT NOT NULL, 
	QUESTION_TOPIC_ID INT NOT NULL,
	QUESTION_TEXT VARCHAR(250) NOT NULL,
	DATE_CREATED TIMESTAMP DEFAULT NOW() NOT NULL,
	IS_EXTRA BOOLEAN DEFAULT FALSE NOT NULL,
	
	FOREIGN KEY (ADMINISTRATOR_ACCOUNT_ID) REFERENCES ADMINISTRATOR_ACCOUNT (ADMINISTRATOR_ACCOUNT_ID),
	FOREIGN KEY (QUESTION_FORMAT_ID) REFERENCES QUESTION_FORMAT (QUESTION_FORMAT_ID),
	FOREIGN KEY (QUESTION_TOPIC_ID) REFERENCES QUESTION_TOPIC (QUESTION_TOPIC_ID)
);

--create Table Survey Word
CREATE TABLE SURVEY_WORD
(
	SURVEY_WORD_ID INT REFERENCES POTENTIAL_SURVEY_WORD (SURVEY_WORD_ID) NOT NULL, 
	SITE_ID INT REFERENCES SITE (SITE_ID) NOT NULL,
	DATE_USED TIMESTAMP DEFAULT NOW() NOT NULL,
	
	PRIMARY KEY (SURVEY_WORD_ID, SITE_ID)
);

-- create table Submitted Survey
CREATE TABLE SUBMITTED_SURVEY
(
	SUBMITTED_SURVEY_ID SERIAL PRIMARY KEY NOT NULL,
	SURVEY_VERSION_ID INT NOT NULL,
	UNIT_ID INT NOT NULL,
	MEAL_ID INT NOT NULL,
	PARTICIPANT_TYPE_ID INT NOT NULL,
	AGE_RANGE_ID INT NOT NULL,
	GENDER_ID INT NOT NULL,
	DATE_ENTERED TIMESTAMP DEFAULT NOW() NOT NULL, 
	CONTACT_STATUS VARCHAR (100) NOT NULL,
	CONTACT_ROOM_NUMBER VARCHAR(50) NULL,
	CONTACT_PHONE_NUMBER VARCHAR(20) NULL,
	
	FOREIGN KEY (SURVEY_VERSION_ID) REFERENCES SURVEY_VERSION (SURVEY_VERSION_ID),
	FOREIGN KEY (AGE_RANGE_ID) REFERENCES AGE_RANGE (AGE_RANGE_ID),
	FOREIGN KEY (UNIT_ID) REFERENCES UNIT (UNIT_ID),
	FOREIGN KEY (MEAL_ID) REFERENCES MEAL (MEAL_ID),
	FOREIGN KEY (PARTICIPANT_TYPE_ID) REFERENCES PARTICIPANT_TYPE (PARTICIPANT_TYPE_ID),
	FOREIGN KEY (GENDER_ID) REFERENCES GENDER (GENDER_ID)
);

-- create table Question Selection
CREATE TABLE QUESTION_SELECTION
(
	QUESTION_SELECTION_ID SERIAL PRIMARY KEY NOT NULL,
	QUESTION_ID INT NOT NULL,
	QUESTION_SELECTION_TEXT VARCHAR(100) NOT NULL,
	QUESTION_SELECTION_VALUE VARCHAR(100) NOT NULL,
	
	FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION (QUESTION_ID)
);

-- create table Survey Question
CREATE TABLE PARTICIPANT_RESPONSE
(
	SUBMITTED_SURVEY_ID INT NOT NULL REFERENCES SUBMITTED_SURVEY (SUBMITTED_SURVEY_ID),
	QUESTION_ID INT NOT NULL REFERENCES QUESTION (QUESTION_ID),
	PARTICIPANT_ANSWER VARCHAR(100) NULL,
	
	PRIMARY KEY (SUBMITTED_SURVEY_ID, QUESTION_ID)
);

-- create table Survey Question
CREATE TABLE SURVEY_QUESTION
(
	SURVEY_VERSION_ID INT NOT NULL REFERENCES SURVEY_VERSION (SURVEY_VERSION_ID),
	QUESTION_ID INT NOT NULL REFERENCES QUESTION (QUESTION_ID),
	
	PRIMARY KEY (SURVEY_VERSION_ID, QUESTION_ID)
);

-- Create Webmaster
INSERT INTO ADMINISTRATOR_ACCOUNT (USERNAME, ADMIN_PASSWORD, FIRST_NAME, LAST_NAME, DATE_CREATED, DATE_MODIFIED)
VALUES ('webmaster', crypt('password', gen_salt('bf')), 'Web', 'Master', Now(), NOW());

--Insert security roles
INSERT INTO security_role (security_description)
VALUES ('Standard Administrator');
INSERT INTO security_role (security_description)
VALUES ('Master Administrator');


--assign webmaster to Master ADministrator role
INSERT INTO ADMINISTRATOR_ROLE (ADMINISTRATOR_ACCOUNT_ID, SECURITY_ROLE_ID, DATE_MODIFIED)
VALUES (1, 2, NOW());

--create misericordia's site
INSERT INTO SITE (SITE_NAME, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('Misericordia Hospital', Now(), 1);

--creates Misericordia's units
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('8E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('7E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('5W', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('7W', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('6E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('6W', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('5E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('3E', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('3N', 1, Now(), 1);
INSERT INTO UNIT (UNIT_NUMBER, SITE_ID, DATE_MODIFIED, ADMINISTRATOR_ACCOUNT_ID)
VALUES ('ED', 1, Now(), 1);

--create potential survey words
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'sunshine', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'flower', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'supper', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'sleepy', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'hungry', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'happy', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'orange', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'friend', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'spring', Now());
INSERT INTO POTENTIAL_SURVEY_WORD(ADMINISTRATOR_ACCOUNT_ID, SURVEY_ACCESS_WORD, DATE_MODIFIED)
VALUES (1, 'circle', Now());

--create question formats
INSERT INTO QUESTION_FORMAT(QUESTION_FORMAT_NAME)
VALUES ('choice');
INSERT INTO QUESTION_FORMAT(QUESTION_FORMAT_NAME)
VALUES ('text');
INSERT INTO QUESTION_FORMAT(QUESTION_FORMAT_NAME)
VALUES ('demo');


--create question topics
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Variety');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Taste');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Temperature');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Appearance');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Staff Helpfulness');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Variety');
INSERT INTO QUESTION_TOPIC(QUESTION_TOPIC_DESCRIPTION)
VALUES('Variety');




--create the empty survey version
INSERT INTO SURVEY_VERSION(ADMINISTRATOR_ACCOUNT_ID, START_DATE)
VALUES (1, Now());




--create meals
INSERT INTO MEAL(MEAL_NAME)
VALUES ('Breakfast');
INSERT INTO MEAL(MEAL_NAME)
VALUES ('Lunch');
INSERT INTO MEAL(MEAL_NAME)
VALUES ('Supper');
INSERT INTO MEAL(MEAL_NAME)
VALUES ('Tea/Snack');
--value for no selection (?)
INSERT INTO MEAL(MEAL_NAME)
VALUES ('Unspecified');

--create participant types
INSERT INTO PARTICIPANT_TYPE(PARTICIPANT_DESCRIPTION)
VALUES('Patient');
INSERT INTO PARTICIPANT_TYPE(PARTICIPANT_DESCRIPTION)
VALUES('Non-Patient');

--create age-ranges
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION)
VALUES ('Under 18 years');
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION)
VALUES ('18 to 34 years');
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION)
VALUES ('35 to 54 years');
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION)
VALUES ('55 to 74 years');
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION)
VALUES ('Over 75 years');
INSERT INTO AGE_RANGE(AGE_RANGE_DESCRIPTION)
VALUES ('Prefer not to Answer');

--create genders
INSERT INTO GENDER(GENDER_DESCRIPTION)
VALUES ('Male');
INSERT INTO GENDER(GENDER_DESCRIPTION)
VALUES ('Female');
INSERT INTO GENDER(GENDER_DESCRIPTION)
VALUES ('Other');
INSERT INTO GENDER(GENDER_DESCRIPTION)
VALUES ('Prefer not to Answer');






--create dummy submitted surveys
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 1, 1, 1, 3,3,Now(), 'no', null, null);
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 2, 3, 1, 1,1,Now(), 'contact', '222', '8883333');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 3, 3, 2, 4,2,Now(), 'no', null, null);
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 4, 2, 1, 2,4,Now(), 'contact', '333', '1110000');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 5, 4, 1, 5,2,Now(), 'contact', '000', '4444444');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 6, 2, 2, 2,2,Now(), 'contact', '2', '2');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 7, 3, 1, 3,3,Now(), 'contact', '3', 'three');
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 8, 5, 2, 4,4,Now(), 'no', null, null);
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 9, 1, 2, 1,4,Now(), 'no', null, null);
INSERT INTO SUBMITTED_SURVEY(SURVEY_VERSION_ID, UNIT_ID, MEAL_ID, PARTICIPANT_TYPE_ID, AGE_RANGE_ID, GENDER_ID, DATE_ENTERED,
							CONTACT_STATUS, CONTACT_ROOM_NUMBER, CONTACT_PHONE_NUMBER)
VALUES (1, 10, 2, 1, 1,1,Now(), 'no', '111', '1111111');


